# Generated by Django 5.0.4 on 2024-10-27 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engsol', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ranking',
            name='last_update',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
