# Generated by Django 5.0.4 on 2024-10-22 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engsol', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
    ]
